require 'rubygems'
require 'action_controller'
require 'action_controller/test_process'
require File.dirname(__FILE__)+'/../lib/require_permissions'
require 'shoulda'
require 'mocha'
require 'matchy'
